apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "delivery-api.fullname" . }}
  labels:
    {{- include "delivery-api.labels" . | nindent 4 }}
data:
  READINESS_MODE: {{ .Values.config.readinessMode | quote }}
